version: "3.8"
services:
  sveltekit-tailwindcss-static:
    image: sveltekit-tailwindcss-static-build
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: deploy-static-svelte
    ports:
      - 5002:80

  sveltekit-tailwindcss-node:
    image: sveltekit-tailwindcss-node-build
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: deploy-node-svelte
    ports:
      - 5003:3000