version: "3.8"
services:
  sveltekit-tailwindcss:
    image: sveltekit-tailwindcss-dev
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5173"
    volumes:
      - ./src:/var/www/html/src
      - ./static:/var/www/html/static
      - ./vite.config.ts:/var/www/html/vite.config.ts
      - ./postcss.config.js:/var/www/html/postcss.config.js
      - ./tailwind.config.js:/var/www/html/tailwind.config.js
      - ./tsconfig.json:/var/www/html/tsconfig.json
      - ./svelte.config.js:/var/www/html/svelte.config.js
    command: npm run dev
    environment:
      - PORT=5173
      - HOST=0.0.0.0
